tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'go-delve/delve'
tap 'homebrew/bundle'
tap 'homebrew/core'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'bash-completion'
brew 'bison'
brew 'ccache'
brew 'gmp'
brew 'coreutils'
brew 'pkg-config'
brew 'makedepend'
brew 'openssl'
brew 'libssh2'
brew 'curl'
brew 'pcre2'
brew 'fish'
brew 'gettext'
brew 'pcre'
brew 'git'
brew 'go'
brew 'fzf'
brew 'ghq'
brew 'glide'
brew 'icu4c'
brew 'jpeg'
brew 'libevent'
brew 'libtool'
brew 'libxml2'
brew 'libyaml'
brew 'mas'
brew 'mhash'
brew 'mcrypt'
brew 'mysql'
brew 'nodebrew'
brew 'pbzip2'
brew 'protobuf'
brew 'readline'
brew 'pyenv'
brew 'ruby-build'
brew 'rbenv'
brew 're2c'
brew 'redis'
brew 'tree'
brew 'wget'
brew 'go-delve/delve/delve'
cask '1password'
cask 'appcleaner'
cask 'atom'
cask 'docker-toolbox'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'intellij-idea'
cask 'iterm2'
cask 'kindle'
cask 'rubymine'
cask 'sequel-pro'
cask 'sourcetree'
cask 'webstorm'
cask 'zeplin'
mas 'ToyViewer (5.4.0)', id: 414298354
mas 'Keynote (7.0.5)', id: 409183694
mas 'iMovie (10.1.3)', id: 408981434
mas 'iPhoto (9.6.1)', id: 408981381
mas 'Xcode (8.1)', id: 497799835
mas 'Slack (2.3.1)', id: 803453959
mas 'Pages (6.0.5)', id: 409201541
mas 'GarageBand (10.1.3)', id: 682658836
mas 'Numbers (4.0.5)', id: 409203825
